language: php

sudo: required

before_install:
  - sudo ./travis-install-librdkafka.sh v1.3.0 $HOME

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/librdkafka

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  - RDKAFKA_VERSION=1.0.0
  - RDKAFKA_VERSION=2.0.1
  - RDKAFKA_VERSION=3.0.5
  - RDKAFKA_VERSION=3.1.3
  - RDKAFKA_VERSION=4.0.2

matrix:
  exclude:
    - php: 5.6
      env: RDKAFKA_VERSION=2.0.1
    - php: 5.6
      env: RDKAFKA_VERSION=3.0.0
    - php: 5.6
      env: RDKAFKA_VERSION=3.0.5
    - php: 5.6
      env: RDKAFKA_VERSION=3.1.3
    - php: 5.6
      env: RDKAFKA_VERSION=4.0.2

    - php: 7.0
      env: RDKAFKA_VERSION=1.0.0

    - php: 7.1
      env: RDKAFKA_VERSION=1.0.0

    - php: 7.2
      env: RDKAFKA_VERSION=1.0.0
    - php: 7.2
      env: RDKAFKA_VERSION=2.0.1

    - php: 7.3
      env: RDKAFKA_VERSION=1.0.0
    - php: 7.3
      env: RDKAFKA_VERSION=2.0.1
  fast_finish: true

before_script:
  - pecl install rdkafka-$RDKAFKA_VERSION
  - composer update --prefer-dist --prefer-lowest --prefer-stable
  - composer install --prefer-dist

script: composer test
