language: php

sudo: required

before_install:
  - sudo ./travis-install-librdkafka.sh v0.9.2 $HOME

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/librdkafka

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true

before_script:
  - pecl install rdkafka-2.0.1
  - if [ "$deps" == "low" ]; then composer update --prefer-dist --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-dist; fi

script: composer test
