language: php

sudo: required

before_install:
  - sudo ./travis-install-librdkafka.sh v0.9.2 $HOME

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/librdkafka

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: 7.1
        - php: nightly
    fast_finish: true

before_script:
  - if [[ ! $skip && $PHP = 5.* ]]; then pecl install rdkafka-1.0.0; fi
  - if [[ ! $skip && $PHP = 7.* ]]; then pecl install rdkafka-2.0.1; fi
  - composer update --prefer-dist --prefer-lowest --prefer-stable
  - composer install --prefer-dist

script: composer test
