language: php

sudo: required

before_install:
  - sudo ./travis-install-librdkafka.sh v0.9.2 $HOME

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/librdkafka

matrix:
    include:
        - php: 5.6
          env: RDKAFKA_VERSION=1.0.0
        - php: 7.0
          env: RDKAFKA_VERSION=2.0.1
        - php: 7.1
          env: RDKAFKA_VERSION=2.0.1
        - php: 7.0
          env: RDKAFKA_VERSION=3.0.5
        - php: 7.1
          env: RDKAFKA_VERSION=3.0.5
    fast_finish: true

before_script:
  - pecl install rdkafka-$RDKAFKA_VERSION
  - composer update --prefer-dist --prefer-lowest --prefer-stable
  - composer install --prefer-dist

script: composer test
